language: node_js

env:
  global:
  - NODE_ENV="production"

node_js:
  - 8
  - 10
  - 12
os:
  - windows
  - linux
  - osx
cache: npm
install: npm install --no-optional --no-audit
scripts: npm run build
