language: node_js

env:
  - NODE_ENV=production

matrix:
  fast_finish: true

os:
  - windows
  - linux
  - osx

node_js:
  - 10
  - 12

cache:
  npm: true
  directories:
    - node_modules

install: npm install --no-optional --no-audit

scripts: npm run build
